name = "awanipro-website"
compatibility_date = "2025-12-31"

[env.production.vars]
# Base URL for assets (leave empty for root-relative paths)
# VITE_BASE_URL = "https://your-domain.com"

[vars]
# Web3Forms API Key
VITE_WEB3FORMS_KEY = "6be5f6a6-c4ae-40bf-bc5d-38778cbdd171"
